apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: birdwatches.otomato.link
spec:
  group: otomato.link
  version: v1alpha1
  scope: Namespaced
  names:
    plural: birdwatches
    singular: birdwatch
    kind: BirdWatch
    shortNames:
     - bw
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            service:
              type: string
            metric:
              type: string
            deviation:
              type: number
              format: float
            increment:
              type: integer
              minimum: 1
              maximum: 10
            canary_version:
              type: string
            if_unhealthy:
              type: string
              pattern: '^(freeze|rollback)$'
            interval:
              type: integer
              minimum: 1
              maximum: 600
            
